# Generated by Django 6.0.3 on 2026-03-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con_vive_plus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='inside_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
        migrations.AddField(
            model_name='house',
            name='outside_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
    ]
