# Generated by Django 6.0.3 on 2026-03-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con_vive_plus', '0002_house_inside_image_house_outside_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='house',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='house',
            name='services',
            field=models.TextField(default=''),
        ),
    ]
