# Generated by Django 6.0.3 on 2026-03-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con_vive_plus', '0003_house_description_house_is_available_house_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='agent_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='house',
            name='agent_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='agent_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
